# -*- coding: utf-8 -*-
"""Gemini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1emh21TXKdGJ6pLLC90_kR81CVTMT3Vsp
"""

!pip install -q -U google-generativeai

import requests
from readability import Document
from bs4 import BeautifulSoup

url = "https://tw.news.yahoo.com/%E7%94%B0%E9%A6%A5%E7%94%84%E7%94%B0%E8%AA%BF%E6%BC%94%E5%94%B1%E6%9C%83%E3%80%8C%E6%B2%92%E6%83%B3%E5%88%B0%E6%9C%83%E9%80%99%E9%BA%BC%E9%9B%A3%E3%80%8D%EF%BC%9A%E8%AC%9D%E8%AC%9D%E7%8F%BE%E5%A0%B4%E9%82%A3%E9%BA%BC%E5%A4%9A%E7%98%8B%E5%AD%90%E9%99%AA%E6%88%91-125920171.html" # 維基百科通常結構比較規範，Readability 也能處理

print(f"嘗試從網址抓取內容並提取主文: {url}")

try:

    response = requests.get(url, timeout=10)
    response.raise_for_status()


    html_string = response.text

    doc = Document(html_string)

    # doc.summary() 返回的是 HTML 片段
    main_article_html = doc.summary()

    # 提取標題
    title = doc.title()

    print(f"頁面標題: {title}")

    #提取其中的純文字
    soup_main = BeautifulSoup(main_article_html, 'html.parser')


    main_article_text = soup_main.get_text(separator='\n').strip()

    print("\n--- 提取到的主文內容 ---")
    if main_article_text:
        print(main_article_text)
    else:
        print("未能提取到主文內容，可能原因：網頁結構特殊或非文章類型。")
    print("------------------------")


except requests.exceptions.RequestException as e:
    print(f"\n抓取網頁時發生錯誤: {e}")
except Exception as e:
    print(f"\n處理內容時發生錯誤: {e}")